# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: C:\Users\predator\Desktop\kubrnet wprss\kompose-windows-amd64.exe convert -f .\compose.yaml
#     kompose.version: 1.28.0 (c4137012e)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: wordpress
#   name: wordpress
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: wordpress
#   strategy: {}
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: C:\Users\predator\Desktop\kubrnet wprss\kompose-windows-amd64.exe convert -f .\compose.yaml
#         kompose.version: 1.28.0 (c4137012e)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/kubrnetwprss-default: "true"
#         io.kompose.service: wordpress
#     spec:
#       containers:
#         - env:
#               - name: WORDPRESS_DB_HOST
#                 value: db
#               - name: WORDPRESS_DB_NAME
#                 value: wordpress
#               - name: WORDPRESS_DB_PASSWORD
#                 value: wordpress
#               - name: WORDPRESS_DB_USER
#                 value: wordpress
#           image: wordpress:latest
#           name: wordpress
#           ports:
#             - containerPort: 80
#           resources: {}
#       restartPolicy: Always
# status: {}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\predator\Desktop\kubrnet wprss\kompose-windows-amd64.exe convert -f .\compose.yaml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wordpress
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\predator\Desktop\kubrnet wprss\kompose-windows-amd64.exe convert -f .\compose.yaml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/kubrnetwprss-default: "true"
        io.kompose.service: wordpress
    spec:
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: wordpress-data
      containers:
        - env:
            - name: WORDPRESS_DB_HOST
              value: db
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: wordpress
            - name: WORDPRESS_DB_USER
              value: wordpress
          image: wordpress:latest
          name: wordpress
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
          resources: {}
      restartPolicy: Always
